title: christian gr√ºnheit
description: *
show_downloads: false
##remote_theme: benbalter/retlab
##remote_theme: brianmaierjr/long-haul
#remote_theme: jekyller/jasper2
url: https://c.gruenheit.de
baseurl: ""

theme: jekyll-theme-minimal
